v2.0-1 release for sharp-drm, removing dphys-swapfile changes, updating maintainership and description

diff --git a/sharp-drm-2.0/debian/preinst b/sharp-drm-2.0/debian/preinst
--- a/sharp-drm-2.0/debian/preinst
+++ b/sharp-drm-2.0/debian/preinst
@@ -9,11 +9,11 @@ if modprobe -n sharp 2>/dev/null; then
 fi
 
 # Check for swap size on arm64
-if [ "$(uname -m )" == "aarch64" ]; then
-	. /etc/dphys-swapfile
-	if (( CONF_SWAPSIZE < 512 )); then
-		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
-		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
-		exit 1
-	fi
-fi
+#if [ "$(uname -m )" == "aarch64" ]; then
+#	. /etc/dphys-swapfile
+#	if (( CONF_SWAPSIZE < 512 )); then
+#		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
+#		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
+#		exit 1
+#	fi
+#fi
